### PR TITLE
Move assets to static dir to avoid having to use relative paths

### PR DESCRIPTION
**Pull request by zephraph**
Self explanatory.

Being as resources in the static directory is directly transferred to the dist directory moving assets here allows the reference of images without the need to do relative paths.

### CODE REVIEW

**Comment by egoist** [comment]
maybe with `resolve: true` it can be as simple as `` already?

**Comment by zephraph** [comment]
That doesn't work for me

**Comment by zephraph** [comment]
I'll give it another try and report back. It just seems to me that static would be the correct place for your assets.

**Comment by egoist** [comment]
if you import something in `./static` it will cause duplication right? 

For example, `./static/foo.png` ends up `./dist/foo.png` and `./dist/static/media/foo.[hash].png`

**Comment by zephraph** [comment]
That's not my understanding of how it works. The files in static are just moved over into the dist directory, right? They aren't hashed at all. So when you include `/assets/media/foo.png` it just pulls that directly from the dist directory.

**Comment by egoist** [comment]
but when you do `` it will be handled by file-loader

**Pull request closed without merging**
