### PR TITLE
Proxy

### PR DESCRIPTION
**Pull request by yegor-sytnyk**
#14 Add proxy mappings 
proxy mapping for single entry proxy option

Notes:
Implementation based on implementation in create-react-app project
To be able to subscribe to 'upgrade' for express server I had to move app.listen call from dev.js to server.js
Currently if proxy is not a string, vbuild would exit with a warning message (maybe should be handled differently)

### CODE REVIEW

**Comment by egoist** [comment]
Would you mind adding some docs about this to https://github.com/egoist/vbuild.js.org/tree/master/docs ?

**Comment by yegor-sytnyk** [comment]
Hi, sure, will do.

**Comment by yegor-sytnyk** [comment]
I had to add connect-history-api-fallback, so proxy would not try to redirect client-side routes to proxy URL, works the same way as in create-react-app

**Comment by egoist** [comment]
looks nice

**Pull request merged**
